#cloud-config

package_update: true
package_upgrade: true

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/debian/ $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - ufw
  - docker-ce
  - docker-buildx-plugin
  - docker-compose-plugin

write_files:
  - encoding: "b64"
    content: "dmVyc2lvbjogIjMiCnNlcnZpY2VzOgogIGh1YjoKICAgIGltYWdlOiBqZXRicmFpbnMvaHViOjIwMjMuMS4xNzU2OAogICAgcG9ydHM6CiAgICAgIC0gIjgwODA6ODA4MCIKICB5b3V0cmFjazoKICAgIGltYWdlOiBqZXRicmFpbnMveW91dHJhY2s6MjAyMy4xLjE3NTgyCiAgICBwb3J0czoKICAgICAgLSAiODAwMDo4MDgwIgogIHRlYW1jaXR5OgogICAgaW1hZ2U6IGpldGJyYWlucy90ZWFtY2l0eS1zZXJ2ZXI6bGF0ZXN0CiAgICBwb3J0czogCiAgICAgIC0gIjgxMTE6ODExMSIKICB0ZWFtY2l0eS1hZ2VudDoKICAgIGltYWdlOiBqZXRicmFpbnMvdGVhbWNpdHktYWdlbnQ6bGF0ZXN0CiAgdXBzb3VyY2U6CiAgICBpbWFnZTogamV0YnJhaW5zL3Vwc291cmNlOjIwMjAuMS4yMDA2CiAgICBwb3J0czoKICAgICAgLSAiODIyMjo4MDgwIgo="
    owner: "root:root"
    path: "/root/docker-compose.yaml"

  - encoding: "b64"
    content: "W1VuaXRdCkRlc2NyaXB0aW9uPUpldGJyYWlucyBTZXJ2aWNlClJlcXVpcmVzPWRvY2tlci5zZXJ2aWNlIG5ldHdvcmstb25saW5lLnRhcmdldApBZnRlcj1kb2NrZXIuc2VydmljZSBuZXR3b3JrLW9ubGluZS50YXJnZXQKCltTZXJ2aWNlXQpUeXBlPW9uZXNob3QKVXNlcj1yb290CkVudmlyb25tZW50PSJIT01FPXJvb3QiCldvcmtpbmdEaXJlY3Rvcnk9L3Jvb3QKRXhlY1N0YXJ0PS91c3IvYmluL2RvY2tlciBjb21wb3NlIHVwCkV4ZWNTdG9wPS91c3IvYmluL2RvY2tlciBjb21wb3NlIGRvd24KUmVzdGFydD1vbi1mYWlsdXJlClJlc3RhcnRTZWM9MTAKCltJbnN0YWxsXQpXYW50ZWRCeT1tdWx0aS11c2VyLnRhcmdldAo="
    owner: "root:root"
    path: "/etc/systemd/system/jetbrains.service"
    permissions: "0644"

  - encoding: "b64"
    content: "KmZpbHRlcgo6SU5QVVQgQUNDRVBUIFswOjBdCjpGT1JXQVJEIERST1AgWzA6MF0KOk9VVFBVVCBBQ0NFUFQgWzA6MF0KOkZJTFRFUlMgLSBbMDowXQo6RE9DS0VSLVVTRVIgLSBbMDowXQoKLUYgSU5QVVQKLUYgRE9DS0VSLVVTRVIKLUYgRklMVEVSUwoKLUEgSU5QVVQgLWkgbG8gLWogQUNDRVBUCi1BIElOUFVUIC1wIGljbXAgLS1pY21wLXR5cGUgYW55IC1qIEFDQ0VQVAotQSBJTlBVVCAtaiBGSUxURVJTCgotQSBET0NLRVItVVNFUiAtaSBlbnMzMyAtaiBGSUxURVJTCgotQSBGSUxURVJTIC1tIHN0YXRlIC0tc3RhdGUgRVNUQUJMSVNIRUQsUkVMQVRFRCAtaiBBQ0NFUFQKLUEgRklMVEVSUyAtbSBzdGF0ZSAtLXN0YXRlIE5FVyAtcyAxLjIuMy40LzMyIC1qIEFDQ0VQVAotQSBGSUxURVJTIC1tIHN0YXRlIC0tc3RhdGUgTkVXIC1tIHRjcCAtcCB0Y3AgLS1kcG9ydCAyMiAtaiBBQ0NFUFQKLUEgRklMVEVSUyAtbSBzdGF0ZSAtLXN0YXRlIE5FVyAtbSB0Y3AgLXAgdGNwIC0tZHBvcnQgMjMgLWogQUNDRVBUCi1BIEZJTFRFUlMgLW0gc3RhdGUgLS1zdGF0ZSBORVcgLW0gdGNwIC1wIHRjcCAtLWRwb3J0IDgwIC1qIEFDQ0VQVAotQSBGSUxURVJTIC1tIHN0YXRlIC0tc3RhdGUgTkVXIC1tIHRjcCAtcCB0Y3AgLS1kcG9ydCA0NDMgLWogQUNDRVBUCi1BIEZJTFRFUlMgLWogUkVKRUNUIC0tcmVqZWN0LXdpdGggaWNtcC1ob3N0LXByb2hpYml0ZWQKCkNPTU1JVAo="
    owner: "root:root"
    path: "/etc/iptables.new.conf"
    

runcmd:
  - systemctl enable jetbrains
  - ufw enable
  - ufw allow ssh
  - ufw allow 8080/tcp

power_state:
  delay: "now"
  mode: "reboot"
  message: "First Reboot"
  condition: True
