#cloud-config

package_update: true
package_upgrade: true

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/debian/ $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - ufw
  - docker-ce
  - docker-buildx-plugin
  - docker-compose-plugin

write_files:
  - encoding: "b64"
    content: "${compose_file}"
    owner: "root:root"
    path: "/root/docker-compose.yaml"

  - encoding: "b64"
    content: "${service_file}"
    owner: "root:root"
    path: "/etc/systemd/system/jetbrains.service"
    permissions: "0644"
    

runcmd:
  - systemctl enable jetbrains
  - ufw enable
  - ufw allow ssh
  - ufw allow 8080/tcp
  - ufw allow 8000/tcp
  - ufw allow 8111/tcp
  - ufw allow 8222/tcp

power_state:
  delay: "now"
  mode: "reboot"
  message: "First Reboot"
  condition: True
