version: "3"
name: "testlab"
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  cgit:
    image: woahbase/alpine-cgit
    depends_on:
      - nginx-proxy
    expose:
      - "80"
    ports:
      - "8022:22"
    volumes:
      - ./cgit/home:/home/cgit
      - ./cgit/ssh:/etc/ssh
      - ./cgit/web:/var/www
      - ./cgit/cgitrc:/etc/cgitrc:ro
      - ./cgit/lighttpd.conf:/etc/lighttpd/cgit.conf:ro
      - /etc/hosts:/etc/hosts:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=cgit.testlab.sapeint.xyz
      - VIRTUAL_PORT=80
  hub:
    image: jetbrains/hub:2024.2.35237
    depends_on:
      - nginx-proxy
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=hub.testlab.sapeint.xyz
      - VIRTUAL_PORT=8080
  # Latest is 2024.2.35237
  # Can't use Hub though.
  youtrack:
    image: jetbrains/youtrack:2024.1.32323
    depends_on:
      - nginx-proxy
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=youtrack.testlab.sapeint.xyz
      - VIRTUAL_PORT=8080
  teamcity:
    image: jetbrains/teamcity-server:latest
    depends_on:
      - nginx-proxy
    expose:
      - "8111"
    ports:
      - "8111:8111"
    environment:
      - VIRTUAL_HOST=teamcity.testlab.sapeint.xyz
      - VIRTUAL_PORT=8111
  teamcity-agent:
    image: jetbrains/teamcity-agent:latest
    environment:
      - SERVER_URL=teamcity:8111
  upsource:
    image: jetbrains/upsource:2020.1.2006
    depends_on:
      - nginx-proxy
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=upsource.testlab.sapeint.xyz
      - VIRTUAL_PORT=8080
  onedev:
    image: 1dev/server
    depends_on:
      - nginx-proxy
    expose:
      - "6610"
      - "6611"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./onedev:/opt/onedev
    environment:
      - VIRTUAL_HOST=onedev.testlab.sapeint.xyz
      - VIRTUAL_PORT=6610
  lldap:
    image: lldap/lldap:stable
    depends_on:
      - nginx-proxy
    expose:
      - "17170"
    tmpfs:
      - /data
    environment:
      - VIRTUAL_HOST=lldap.testlab.sapeint.xyz
      - VIRTUAL_PORT=17170
